package mif.vu.lt.psktp1.mybatis.dao;

import java.util.List;
import mif.vu.lt.psktp1.mybatis.model.Song;
import org.mybatis.cdi.Mapper;

@Mapper
public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    int deleteByPrimaryKey(Integer songId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    Song selectByPrimaryKey(Integer songId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    List<Song> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SONG
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    int updateByPrimaryKey(Song record);
}