package mif.vu.lt.psktp1.mybatis.model;

import lombok.Getter;
import lombok.Setter;
import mif.vu.lt.psktp1.entities.Artist;
import mif.vu.lt.psktp1.entities.Song;

import java.util.List;

public class Album {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.ID
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.ALBUM_ARTIST
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    private String albumArtist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.ALBUM_NAME
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    private String albumName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.SONGS_NUMBER
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    private Integer songsNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ALBUM.ARTIST_ID
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    private Integer artistId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.ID
     *
     * @return the value of PUBLIC.ALBUM.ID
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.ID
     *
     * @param id the value for PUBLIC.ALBUM.ID
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.ALBUM_ARTIST
     *
     * @return the value of PUBLIC.ALBUM.ALBUM_ARTIST
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public String getAlbumArtist() {
        return albumArtist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.ALBUM_ARTIST
     *
     * @param albumArtist the value for PUBLIC.ALBUM.ALBUM_ARTIST
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public void setAlbumArtist(String albumArtist) {
        this.albumArtist = albumArtist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.ALBUM_NAME
     *
     * @return the value of PUBLIC.ALBUM.ALBUM_NAME
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public String getAlbumName() {
        return albumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.ALBUM_NAME
     *
     * @param albumName the value for PUBLIC.ALBUM.ALBUM_NAME
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public void setAlbumName(String albumName) {
        this.albumName = albumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.SONGS_NUMBER
     *
     * @return the value of PUBLIC.ALBUM.SONGS_NUMBER
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public Integer getSongsNumber() {
        return songsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.SONGS_NUMBER
     *
     * @param songsNumber the value for PUBLIC.ALBUM.SONGS_NUMBER
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public void setSongsNumber(Integer songsNumber) {
        this.songsNumber = songsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ALBUM.ARTIST_ID
     *
     * @return the value of PUBLIC.ALBUM.ARTIST_ID
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public Integer getArtistId() {
        return artistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ALBUM.ARTIST_ID
     *
     * @param artistId the value for PUBLIC.ALBUM.ARTIST_ID
     *
     * @mbg.generated Wed Mar 30 17:09:18 EEST 2022
     */
    public void setArtistId(Integer artistId) {
        this.artistId = artistId;
    }

    // Added manually
    private Artist artist;
    private List<Song> songList;
}